[project]
name = 'Decentralized-Quantum-Consciousness-Collective'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.collective-thought-consensus]
path = 'contracts/collective-thought-consensus.clar'
clarity_version = 2
epoch = 2.5

[contracts.mind-state-quantization]
path = 'contracts/mind-state-quantization.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-neural-network]
path = 'contracts/quantum-neural-network.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
